



insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'LE JARDIN PECHEUR','5 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'JOYA','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'I BOAT','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'LE RE','325 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'L''ANNEXE','96 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'COIN DES COPAINS','78 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'Fred Test','5 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'L''EVIDENCE CAFE','5 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'CHEZ AURELE','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'PASTEL','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'LE RE','325 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'LE MIROIR','96 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'CHEZ MEME','78 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'TOTTO','5 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'LE NEW-YORK','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'BIG','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'LE RE','325 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'MAISON MERE','96 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'L''ORLEANS','78 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'LE 5','5 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'HARRIET''S CAFE','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'BISTROT GD HOMMES','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'BRASSERIE TOURNY','325 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'BISTROT MIMI','96 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'LEOPOLD','78 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'BONNE MER 2','5 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'BISTROT ANETO','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'LA P''TITE BRASSERIE','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'IBIS STYLE','325 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'LE MIRABELLE','96 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'DOCTEUR GREGOIRE','78 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'CHEZ DUPONT','5 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'AU REVE','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'HEDONIQUE','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'BISTROT DES ANGES','325 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'LE CARRE','96 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'EL NACIONAL','78 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'CAMBRIDGE  ARMS','5 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'COPINE CLAUDE','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'BISTROT  FROMAGER','3 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'MOLLY MALONE''S','325 rue de la paix','f.buono@wanadoo.com');
insert into restaurant(id,name,adresse,email) values (restaurant_seq_id.nextval, 'ZAC','96 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'ARKOSE','78 rue de la paix','f.buono@wanadoo.com');
insert into restaurant (id,name,adresse,email)values (restaurant_seq_id.nextval, 'CAFE DE LA PLACE','5 rue de la paix','f.buono@wanadoo.com');


insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',1);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',1);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',1);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',1);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',1);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',1);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',1);

insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',2);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',2);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',2);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',2);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',2);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',2);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',2);

insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',3);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',3);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',3);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',3);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',3);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',3);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',3);

insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',4);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',4);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',4);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',4);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',4);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',4);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',4);


insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',5);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',5);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',5);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',5);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',5);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',5);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',5);


insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 3,'2020-01-01',6);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 2,'2020-01-01',6);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 5,'2020-01-01',6);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 7,'2020-01-01',6);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 5,'2020-01-01',6);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 4,'2020-01-01',6);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 3,'2020-01-01',6);

insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',7);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',7);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',7);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',7);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',7);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',7);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',7);

insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',8);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',8);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',8);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',8);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',8);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',8);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',8);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',9);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',9);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',9);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',9);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',9);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',9);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',9);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',10);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',10);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',10);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',10);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',10);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',10);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',10);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',11);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',11);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',11);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',11);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',11);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',11);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',11);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',12);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',12);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',12);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',12);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',12);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',12);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',12);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',13);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',13);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',13);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',13);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',13);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',13);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',13);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',14);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',14);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',14);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',14);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',14);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',14);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',14);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',15);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',15);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',15);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',15);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',15);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',15);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',15);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',16);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',16);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',16);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',16);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',16);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',16);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',16);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',17);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',17);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',17);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',17);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',17);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',17);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',17);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',18);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',18);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',18);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',18);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',18);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',18);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',18);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',19);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',19);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',19);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',19);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',19);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',19);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',19);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',20);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',20);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',20);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',20);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',20);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',20);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',20);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',21);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',21);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',21);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',21);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',21);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',21);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',21);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',22);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',22);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',22);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',22);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',22);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',22);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',22);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',23);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',23);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',23);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',23);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',23);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',23);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',23);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',24);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',24);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',24);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',24);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',24);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',24);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',24);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',25);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',25);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',25);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',25);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',25);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',25);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',25);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',26);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',26);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',26);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',26);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',26);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',26);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',26);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',27);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',27);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',27);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',27);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',27);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',27);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',27);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',28);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',28);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',28);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',28);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',28);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',28);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',28);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',29);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',29);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',29);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',29);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',29);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',29);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',29);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',30);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',30);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',30);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',30);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',30);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',30);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',30);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',31);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',31);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',31);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',31);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',31);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',31);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',31);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',32);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',32);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',32);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',32);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',32);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',32);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',32);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',33);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',33);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',33);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',33);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',33);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',33);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',33);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',34);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',34);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',34);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',34);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',34);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',34);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',34);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',35);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',35);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',35);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',35);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',35);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',35);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',35);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',36);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',36);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',36);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',36);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',36);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',36);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',36);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',37);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',37);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',37);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',37);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',37);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',37);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',37);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',38);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',38);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',38);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',38);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',38);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',38);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',38);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',39);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',39);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',39);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',39);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',39);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',39);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',39);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',40);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',40);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',40);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',40);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',40);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',40);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',40);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',41);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',41);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',41);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',41);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',41);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',41);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',41);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',42);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',42);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',42);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',42);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',42);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',42);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',42);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',43);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',43);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',43);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',43);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',43);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',43);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',43);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,0, 0,'2020-01-01',44);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,1, 0,'2020-01-01',44);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,2, 0,'2020-01-01',44);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,3, 0,'2020-01-01',44);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,4, 0,'2020-01-01',44);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,5, 0,'2020-01-01',44);
insert into matrix (id,DAY, QUANTITY, START_DATE,RESTAURANT_ID )values (matrix_seq_id.nextval,6, 0,'2020-01-01',44);
/*






*/